spring:
  application:
    name: orderManagement

  datasource:
    url: jdbc:postgresql://localhost:5433/assignment
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public
    validate-on-migrate: true
    out-of-order: true
    repair-on-migrate: true

  logging:
  level:
    com.order.management: DEBUG

